kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: ui-extensions
  namespace: fleet-local
spec:
  repo: ssh://git@git-ssh.atoy.lol/home/ui-extensions.git
  branch: main
  clientSecretName: private-key
  targets:
  - name: local
    clusterSelector: {}
  paths:
  - "./crds"
  - "./operator"