kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: ui-extensions
  namespace: fleet-local
spec:
  repo: https://github.com/atoy3731/fleet-ui-extensions.git
  branch: main
  targets:
  - name: local
    clusterSelector: {}
  paths:
  - "./crds"
  - "./operator"
  - "./repo"
  - "./stigatron-ui"